/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClassroomFrame.java
 *
 * Created on Oct 19, 2011, 11:29:28 AM
 */
package teletutor.classroommanager.UI;

import javax.swing.SwingUtilities;
import teletutor.classroommanager.impl.ClassroomManager;

/**
 *
 * @author Rae
 */
public class ClassroomFrame extends javax.swing.JFrame {

    /** Creates new form ClassroomFrame */
    public ClassroomFrame(final ClassroomManager crman) {
        initComponents();
        
        setTitle("ClassroomManager: " + crman.getChannel().getGroupName()
                + ", " + crman.getChannel().getChannelName() + " on " + crman.getChannel().getGroupName());
        
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                tabbedPane.addTab("Class View", null, crman.getMemberListPanel(), "Shows the state of the classroom, along "
                        + "with all the members");
            }
        });
        
        // TODO add the tab for open discussion
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
