/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MemberListPanel.java
 *
 * Created on Oct 19, 2011, 11:03:29 AM
 */
package teletutor.classroommanager.UI;

import java.awt.FlowLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author Rae
 */
public class MemberListPanel extends javax.swing.JPanel {

    /** Creates new form MemberListPanel */
    public MemberListPanel() {
        initComponents();
        
        listPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 20));
    }
    
    public void addMember(final MemberProxy mProxy) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                listPanel.add(mProxy.getThumbPanel());
                listPanel.repaint();
            }
        });
    }
    
    public void removeMember (final MemberProxy mProxy) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                listPanel.remove(mProxy.getThumbPanel());
                listPanel.repaint();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        listPanel = new javax.swing.JPanel();
        curiousButton = new javax.swing.JButton();

        jLabel1.setText("List of Members:");

        scrollPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        listPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(listPanel);

        curiousButton.setText("Request Audio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(curiousButton)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(curiousButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton curiousButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
